### ISSUE TITLE
--cfg_path issue

### ISSUE THREAD

**Issue by ArthurMorgan-2023** [mwritescode/smart-contracts-vulnerabilities#1]
trying to run it on colab. i am using the default.yaml file.  running using the following command. 

!python3 "/content/smart-contracts-vulnerabilities-main/main.py" --cfg_path "/content/smart-contracts-vulnerabilities-main/src/config/experiments/default.yaml"

its giving me the following error: 
usage: main.py
       [-h]
       cfg_path
main.py: error: unrecognized arguments: --cfg_path

i have tried giving the path without quotes (""). but its still giving me argument error as 'unrecognized arguments'. 
![180220231701_86](https://user-images.githubusercontent.com/124337476/219858180-5cdc02b2-7f04-41f1-9cd9-d29c67a441c7.png)

**Comment by mwritescode** [comment]
Hi!
Thanks for pointing this out. 
It appears that there's an error in our readme, cfg_path is actually passed to the script as a positional argument so the correct way to run the code  on colab is

`!python3 "/content/smart-contracts-vulnerabilities-main/main.py" "/content/smart-contracts-vulnerabilities-main/src/config/experiments/default.yaml"`

I'll fix the readme asap.
